[programs.localnet]
mymoneydapp = "7Hqh6QVDRomntKJYwvQNH2xxwG1AfRxsyeK3E1r1yxjC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ssm-user/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
